schema:
  - type: CharField
    attributes:
      label: description
      required: True
  - type: ChoiceField
    attributes:
      choices:
        - healthy
        - warning
        - failed
        - pending
      label: icon
  - type: CharField
    attributes:
      label: text
      widget: Textarea
contents:
