contents:
- description: ddd
  icon: healthy
  id: 1
  text: dd
schema:
- attributes:
    label: description
    required: true
  type: CharField
- attributes:
    choices:
    - healthy
    - warning
    - failed
    - pending
    label: icon
  type: ChoiceField
- attributes:
    label: text
    widget: Textarea
  type: CharField
